name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d236c50d8f5697658af70389e88270e86d6239b2ecc8b22315bbc1648c5cb87f"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
