name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "052662e6036af7077aac9f0571be9d60d659e2a29a1e40452b12f644a806edbe"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
