name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a13c38a41b11783c8bd979dfa7f0182ac681fa381d9d6fe693c2469ba8bd82b6"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
