name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03de79f26f229d3d0a115c42b01ac674ce2fa485528d7a3b1a1457f2768cc1f7"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
