name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "322a8fb91fa2da4fdd1afa56fb3ff4c0e00659bba0ac696a1004cb26abf2f1b9"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
