name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06c2ba37da476d99fc48399e1a512c0810db8902c2acad96043c895fe4f3f74f"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
