name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a16196936b095e5038b4505fc50574641abd8e440d7d3015d5901edcc027a52a"

[versions]
fabric = "0.14.20"
minecraft = "1.19.4"
