name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5449df19eaf2b97fc990ec9e6e3fc55f2764ef07189f19d8fda1a51e1c78d70"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
