name = "MioPack"
author = "rexlManu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7073ddedb55231586efa7fec53c6c6a9af870a468426145fcfe85da769b226e7"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"
